name: namma_metro
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.1.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  smooth_page_indicator: ^1.1.0
  otp_text_field: ^1.1.3
  flutter_otp_text_field: ^1.1.1
  qr_flutter: ^4.1.0
  flutter_native_splash: ^2.3.7
  firebase_core: ^2.24.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
flutter_native_splash:
  color: "#f7f6f1"
  color_dark: "#272727"
  image: lib/assets/logo.png
  image_dark: lib/assets/logo.png

  android_12:
    image: lib/assets/logo.png
    icon_background_color: "#f7f6f1"
    image_dark: lib/assets/logo.png
    icon_background_color_dark: "#272727"

flutter:
  uses-material-design: true

  assets:
    - lib/assets/
