name: namma_metro
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.1.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  smooth_page_indicator: ^1.1.0
  otp_text_field: ^1.1.3
  flutter_otp_text_field: ^1.1.1
  qr_flutter: ^4.1.0
  flutter_native_splash: ^2.3.7
  firebase_core: ^2.24.2
  get: ^4.6.6
  shared_preferences: ^2.2.2
  firebase_auth: ^4.16.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  test: ^1.15.4

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - lib/assets/
