// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCrtVRp-GxDMw9jCwVGN9VWDjakxK7wKvA',
    appId: '1:740755234860:web:af1de39a4bc90c2fe8b189',
    messagingSenderId: '740755234860',
    projectId: 'namametro-e92ed',
    authDomain: 'namametro-e92ed.firebaseapp.com',
    storageBucket: 'namametro-e92ed.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDUFYr9XVj-gWLG4Cp7iaWO0Pvj65dA-Lk',
    appId: '1:740755234860:android:667fb8e8812fcad6e8b189',
    messagingSenderId: '740755234860',
    projectId: 'namametro-e92ed',
    storageBucket: 'namametro-e92ed.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD_c0Mo8HPVFUA296k_S6b2ZF1hapKBbvk',
    appId: '1:740755234860:ios:7fd4558718386715e8b189',
    messagingSenderId: '740755234860',
    projectId: 'namametro-e92ed',
    storageBucket: 'namametro-e92ed.appspot.com',
    iosBundleId: 'com.example.nammaMetro',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD_c0Mo8HPVFUA296k_S6b2ZF1hapKBbvk',
    appId: '1:740755234860:ios:e8e7982eed5563f0e8b189',
    messagingSenderId: '740755234860',
    projectId: 'namametro-e92ed',
    storageBucket: 'namametro-e92ed.appspot.com',
    iosBundleId: 'com.example.nammaMetro.RunnerTests',
  );
}
